import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import newStyles from "@/styles/newStyles.module.css"
import Script from 'next/script'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Hello world</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script src='simplejs.js'strategy="lazyOnload">

      </Script>
      <main className={styles.main}>
      <ul className={newStyles.ulItem}>
            <li><a href="#">Home</a></li>
            <li><a href="#">Posts</a></li>
            <li><a href="#">About</a></li>
            <li><a href="#">Contacts</a></li>
      </ul>
        <div className={styles.center}>
          <h1 style={{color:"burlywood",fontStyle:"italic",fontWeight:"bold"}}>Welcome to my BlogEra</h1>
        </div>
        <h3>
          Learn About ReactJs
        </h3>
        <p>A Popular,most used js library</p>
        <hr/>
        <h3>
          Learn About AngularJs
        </h3>
        <p>A Popular,most used js framework</p>
        <hr/>
        <h3>
          Learn About Javascript
        </h3>
        <p>A popular scripting language</p>

      </main>
    </>
  )
}
