import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Script from 'next/script'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
    <style jsx>
{
  `
  .blogItem{
    margin:8px
  }
  `
}
    </style>
      <Head>
        <title>Hello world</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Script src='simplejs.js'strategy="lazyOnload">
      </Script> */}
      <main className={styles.main}>
        <div className={styles.center}>
          <h1 style={{color:"burlywood",fontStyle:"italic",fontWeight:"bold"}}>Welcome to my BlogEra</h1>
        </div>
      </main>
    </>
  )
}
